### ISSUE TITLE
Display single kanji keyword in default mode

### ISSUE THREAD

**Issue by kavinvin** [klieret/rtk-lookup#1]
When querying for single kanji in default mode, the result will be the same as the input.
```
(default) 女

    女

```
Maybe I missed something, but it seems not very useful. So I think it might be better to also return the keyword according to the kanji the same as in the multiple kanji condition.
```
(default) 女

    女: woman

```

**Comment by kavinvin** [comment]
I don't know if the whole application will continue to work correctly, as I don't know most of the intended behavior, but I'll leave my pull request here anyway. #2

**Comment by klieret** [comment]
Hi! Thanks for the suggestion. I'm sure there's a lot to improve about this application. I've started this quite some time ago.... I'd definitely appreciate and support developing this further though, if there's interest :)

**Comment by klieret** [comment]
Closed with PR https://github.com/klieret/rtk-lookup/pull/2 . Thanks a lot :1st_place_medal:
